"""add Payee model and payee_id to transactions

Revision ID: 05d40e2af386
Revises: 38057d79def5
Create Date: 2025-07-19 17:07:05.753234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d40e2af386'
down_revision = '38057d79def5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_payee_id', 'payee', ['payee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_payee_id', type_='foreignkey')
        batch_op.drop_column('payee_id')

    op.drop_table('payee')
    # ### end Alembic commands ###
