"""Add Plan model and relationships for multi-plan support

Revision ID: 2e8981baa137
Revises: 1439262c4d70
Create Date: 2025-06-24 14:08:36.587009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2e8981baa137'
down_revision = '1439262c4d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_active_plan_id', 'plan', ['active_plan_id'], ['id'])
        batch_op.drop_column('budget_pref')
        batch_op.drop_column('monthly_income')
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('monthly_income', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('budget_pref', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint('fk_user_active_plan_id', type_='foreignkey')
        batch_op.drop_column('active_plan_id')

    # ### end Alembic commands ###
