"""Add date_created to User model

Revision ID: 38057d79def5
Revises: 9930b5681a9f
Create Date: 2025-07-14 23:14:06.236090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38057d79def5'
down_revision = '9930b5681a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
